### PR TITLE
Fix of possible memory leaks regarding the StreamManager 

### PR DESCRIPTION
**Pull request by birche**
…when excessively loading new Pdf documents.

I've made a quick fix making sure it unregisters on gc.

### CODE REVIEW

**Comment by IanYates** [comment]
The PdfDocument class already implements IDisposable.  Disposing of a field within a finalizer doesn't make sense, as by the time the CLR has reached the stage of running the finalizer, you're already past the stage where disposing of the file makes sense.
Did you run into some problems with the PdfDocument class?  Were you disposing of your instances?

See http://stackoverflow.com/a/29012764/1053381 for some info.   Also see http://www.devx.com/dotnet/Article/33167/0/page/2

**Comment by birche** [comment]
You're right of course but what if the PdfDocument instance is never disposed? You'll end up with a reference to the underlying FileStream object in the static StreamManager, thus preventing it from being cleaned up from memory.

I suppose it's arguable whether it's the right thing to do by forcing users to explicitly dispose unused objects - yes, it usually is - but in this case it's a private implementation that is cause of a possible memory leak, which can be avoided if the finalizer makes sure it unregisters the FileStream object as a, sort of, last resort.

**Comment by IanYates** [comment]
Good point!
That's me jumping in with both feet and not knowing the codebase :)

I guess you could consider the StreamManager as an unmanaged resource (since it's certainly doing the unmanaged DLL memory management).
So in that case, yes, you definintely want some cleanup in a finalizer.

It might be best though to put this logic into the PdfFile class since it's the PdfFile class that really has the unmanaged resources.  I can see calls to GC.SuppressFinalize in PdfDocument and PdfFile but neither had a finalizer anyway.  Keeping the cleanup logic (and comments relating to why it's important) near the unmanaged pointers, static class state changes, etc might help later when someone else needs to grok this behaviour.

Having it in PdfFile means that if that PdfFile reference does get utilised even after PdfDocument is let go (but not disposed) then you won't hit a funny ObjectDisposed exception.  Admittedly that would be pretty wonky use of the library.

**Comment by pvginkel** [comment]
The way `PdfRenderer` is constructed is that it does **not** take ownership of the `PdfDocument`. So, it's the responsibility of the caller to make sure that the `PdfDocument` is correctly disposed. This is modeled after e.g. how the `PictureBox` control works. That has a property `Image`, but the image provided there will never be disposed by the `PictureBox` since it does not become the owner of the image.

So, what you can do is:

When setting the `Document`:

    if (pdfViewer1.Document != null)
        pdfViewer1.Document.Dispose();
    pdfViewer1.Document = /* new document */.

In the constructor of the form:

    public MainForm()
    {
        Disposed += (s, e) =>
        {
            if (pdfViewer1.Document != null)
            {
                pdfViewer1.Document.Dispose();
                pdfViewer1.Document = null;
            }
        };
    }

Closing this merge request because of the above and the comment made by @IanYates

**Pull request closed without merging**
