### PR TITLE
Adding buttons for fitting and rotating page

### PR DESCRIPTION
**Pull request by bryjamus**
I add buttons to toolbar which are responsible for fitting and rotating page. Fitting page is made by one of tree states:
1. Fit width
2. Fit height
3. Fit best - which use one of above two states depending on control and document scale factor (look at method CalculateZoomMode in PdfRenderer.cs).

### CODE REVIEW

**Comment by bryjamus** [comment]
If changes are ok with you please make new Nuget version after merge.

**Comment by bryjamus** [comment]
One more think which you should know: 
* fit_xxx.png are downloaded from [IconArchive](http://www.iconarchive.com/show/oxygen-icons-by-oxygen-icons.org/Actions-zoom-fit-width-icon.html) and are on LGPL License
* rotate_xxx.png are downloaded from [IconArchive](http://www.iconarchive.com/show/farm-fresh-icons-by-fatcow/shape-rotate-clockwise-icon.html) and are on CC Attribution 4.0 License

**Comment by pvginkel** [comment]
Thank you for your pull request. However, the changes to the toolbar should not be added to the project. I know this is a bit confusing to people, and I should really document the reason for this and how you can work around this. I've just now created an issue for this at #41. Please have a look at that for an explanation.

I do however like the best fit change. If it is possible for you to remove the changes to the `PdfViewer` control, I'm happy to accept the pull request. Sorry for the confusion.

**Comment by bryjamus** [comment]
I revert changes and implemented only "Fit Best" in PdfRenderer class.

As I understand as you release new version we should use PdfRenderer instead PdfViewer and make our own toolbar for this control?

**Pull request merged**
