### PR TITLE
Added basic editing and save capability. Rotate or delete pages.

### PR DESCRIPTION
**Pull request by peter0302**
Glad to be of help. I added several of the APIs that I know of for editing and saving to the NativeMethods collection and also added DeletePage and RotatePage to PdfDocument. This should be plenty to get you started, but there is a lot more that can be done of course.

### CODE REVIEW

**Comment by peter0302** [comment]
I should also note that in this branch I changed the PdfFile class to always use the FPDF_LoadCustomDocument method and a generic Stream. (This also obviates any need for the derived PdfFile classes). This way you can open a PDF file with any kind of Stream (even something off a network, encrypted, whatever you like) and the delegate takes care of feeding the data to pdfium. There's some fancy COM interop going on in order to pass the Stream around so it actually gets to the delegate, but it works like a charm. I use this to read PDFs off of Azure blobs, among other things.

**Comment by rearintok** [comment]
please merge the pull request.

**Comment by pvginkel** [comment]
Sorry for the delay. Thank you for the merge request; looks very nice. I've made a few changes:

* I've cleaned up some things (removed the unused files, some small checks, some minor refactoring);
* I removed the "fancy COM interop" and replaced it with a registry to create `int` handles for `Stream`'s. Looks a lot simpler and doesn't interfere with the GC as much;
* I've implemented rotate and delete on `PdfDocument` and added a few menu options in the demo application to demo these new methods.

**Comment by peter0302** [comment]
Oh that's a much more elegant solution to passing the Stream to the native code!

Glad to be of help.

Sent from my iPhone

On Jun 17, 2016, at 12:59 AM, Pieter van Ginkel <notifications@github.com<mailto:notifications@github.com>> wrote:


Sorry for the delay. Thank you for the merge request; looks very nice. I've made a few changes:

  *   I've cleaned up some things (removed the unused files, some small checks, some minor refactoring);
  *   I removed the "fancy COM interop" and replaced it with a registry to create int handles for Stream's. Looks a lot simpler and doesn't interfere with the GC as much;
  *   I've implemented rotate and delete on PdfDocument and added a few menu options in the demo application to demo these new methods.

-

**Pull request merged**
