### PR TITLE
Added WPFDemo based on version 1.4.0.0

### PR DESCRIPTION
**Pull request by mafshin**
@pvginkel I just rebased from version 1.4.0.0 and added WPFDemo

### CODE REVIEW

**Comment by shameleo** [comment]
Hi mafshin, remember me? I looked through your WPF demo, and made it work. I will share my code soon.

**Comment by mafshin** [comment]
@shameleo No I don't but willingly waiting to see your achievements.

**Comment by shameleo** [comment]
@mafshin Look commit in my fork: https://github.com/shameleo/PdfiumViewer/commit/fc4421a62f9deb689e9d4a08a53c291f8ab27f43

**Comment by shameleo** [comment]
I create BitmapSource instance at once, without intermediate bitmap. It gives significant speed up. But to be able return BitmapSource i had to add some additional dependencies to PdfiumViewer accembly. Furthermore i had to upgrate targeting framework. It can be undesirable, that's why i'm not going to do pull request. Maybe use should return byte[] instead of BitmapSource.

**Comment by mafshin** [comment]
@shameleo , The work is impressive and you just finished what I missed. Thanks.

Old: 30 ms per page
New: 20 ms per page
%33 speedup :+1:  

capture

I created a new branch [NET3.5Branch](https://github.com/IRISTed/PdfiumViewer/tree/NET3.5Branch) and merged your changes into that.

**Comment by pvginkel** [comment]
Very nice. At the moment I don't have time to look at this but I'm going to
merge these the first chance i have.

**Comment by shameleo** [comment]
@mafshin  @pvginkel  Wait a little. Iim going to try to make it better

**Comment by pvginkel** [comment]
Cool

**Comment by mafshin** [comment]
@shameleoو @pvginkel I commited all changes into my [master](https://github.com/IRISTed/PdfiumViewer/tree/master) branch. It's based on .NET 2.0 and has two overloads one returning a byte[] and the other a Bitmap. Now WinForm users can benefit from FDIB, too.

**Pull request closed without merging**
