### PR TITLE
Added support for direct render into Bitmap

### PR DESCRIPTION
**Pull request by mafshin**
Imported some other methods for Bitmap rendering and added a new WPF
demo project to test these new methods performance.

There are two ways to render to Bitmap

1. Using FPDF_RenderPage method with a Memory Device Context
2. Using FPDF_RenderPageBitmap method with a Foxit Device Independent
Bitmap (Not Working Yet)

### CODE REVIEW

**Comment by pvginkel** [comment]
Have a look at #6. That appears to be solving the same issue (roughly) and I've implemented support for this directly into PdfDocument.

**Comment by mafshin** [comment]
Thanks @pvginkel. Your new Render implementation is nearly same as mine but more accurate. There's also a FPDF_RenderPageBitmap method in Pdfium for direct rendering into bitmap,  I partially ported it but failed in converting the resulting BGRA FDIB into .NET Bitmap. Please take a look at it too. (https://github.com/IRISTed/PdfiumViewer/blob/master/PdfiumViewer/PdfDocument.cs)

**Comment by pvginkel** [comment]
Yes, you're right. To solve #6 I actually found your question on stackoverflow and used that as a starting point. I didn't realize this until I looked at your pull request :). If you're interested I do like the WPF demo application you wrote. Could you rebase onto the latest version and use the new render overload?

About the BGRA method. Could you explain the purpose of this? Maybe I can help getting it to work.

**Comment by mafshin** [comment]
@pvginkel  Surely I will do it.

According to Foxit [manual](http://cdn01.foxitsoftware.com/pub/foxit/manual/enu/FoxitPDF_SDK20_Guide.pdf) `FPDF_RenderPageBitmap` job is to "Render contents in a page to a device-independent bitmap":

Foxit PDF SDK doesn’t directly support X-Windows output, however, you can use the Foxit Device Independent Bitmap (FXDIB) features provided in the SDK to render any PDF page into a bitmap device. You can then transfer the bitmap onto X-Windows surface, or image file, or other type of devices. Before you can use a bitmap device, you need to create one and you can use the FPDFBitmap_Create function to do that. Foxit PDF SDK supports two types of bitmaps: RGB bitmap and ARGB bitmap, you can choose which format you want to use when you create the bitmap. When the bitmap is created, you need to fill the buffer with the background that you like. Normally it can be a white background or a non-colored background (if alpha channel is used). Now you can use it in the FPDF_RenderPageBitmap function. This function is pretty much the same as the FPDF_RenderPage function, but instead of sending output to a Windows device, it outputs to the bitmap device.

There's also a sample in that manual which I exactly ported it to make it work bu failed.

Currently, the Render overload for bitmap perform it in 30 milliseconds per page in my tests. Since there's a specific method for this job in Pdfium, I hope we can reduce this render time by using that specific method.

**Comment by pvginkel** [comment]
Ah, so it's about performance. Even though 30ms doesn't sound that bad, it is interesting to see whether we can get this down a bit.

At the moment work is crazy, but I'll keep this in mind and have a look at it as soon as I can. Thanks for the info.

**Comment by mafshin** [comment]
@pvginkel , The user @shameleo just completed what I started on implementing FDIB rendering and I merged his fork to a new branch [here](https://github.com/IRISTed/PdfiumViewer/tree/NET3.5Branch). It's based on .NET3.5 to render directly into `BitmapSource`. I will try to write a version of that by returning byte[] to keep it on .NET2.0.

**Pull request closed without merging**
